### PR TITLE
Added welcome bot

### PR DESCRIPTION
**Pull request by itsIapetus**
Closes Issue number #13

### CODE REVIEW

**Comment by yvkrishna** [comment]
our team will get back tou you shortly. 😄

**Comment by itsIapetus** [comment]
@yvkrishna By when?

**Review by chebroluharika — APPROVED** [review]
LGTM

**Comment by chebroluharika** [comment]
@yvkrishna , Please add relevant labels before you merge it
@itsIapetus Just a heads-up, Please make sure and work with @yvkrishna to install this bot in repository and give proper permissions to it before merging it.

**Comment by itsIapetus** [comment]
Okay, it is installed by the way

**Comment by chebroluharika** [comment]
@itsIapetus Please provide screenshot showing welcomebot under GitHub apps with proper permissions as you said its installed, so that I will merge this PR.

**Comment by itsIapetus** [comment]
image

**Comment by chebroluharika** [comment]
@itsIapetus I believe you have installed app in your github repo, whereas in order to make your change working, you need to install app in flow2ML repo.

**Comment by itsIapetus** [comment]
I have done this before for other repos, and it works

**Comment by chebroluharika** [comment]
Are those repos in your local account?

**Comment by chebroluharika** [comment]
@itsIapetus We need to install GitHub App in Flow2ML repo, for which we need to have write access. PFA below
image
We will take care of it anyways.

> I have done this before for other repos, and it works

May be those repos are under your local account.

**Pull request merged**
