### PR TITLE
deployed tensorflow models

### PR DESCRIPTION
**Pull request by ainy-123**
# Description:

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue no.) 
#76 

## Type of change:

- [x] New feature (non-breaking change which adds functionality)

 
# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by chebroluharika** [comment]
@ainy-123 please add code for how to call this in readme so that users can understand the pipeline. And also add this method present in readme inside flow2ml folder.

**Comment by chebroluharika** [comment]
@yvkrishna can you please review this.

**Review by yvkrishna — COMMENTED** [review]
@ainy-123, Can you put image for the final output

**Comment by yvkrishna** [comment]
@ainy-123, in the similar way, can you work on deploying pytorch method as well

**Comment by yvkrishna** [comment]
> @ainy-123, in the similar way, can you work on deploying pytorch method as well ?

**Pull request merged**
