### PR TITLE
Improved code standards as per PEP8

### LINKED ISSUE #70: Improve code standards as per PEP8
Modify entire code as per PEP8 standard

### PR DESCRIPTION
**Pull request by AshuKV**
# Description:

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #70 

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

 
# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

# Screenshots / Video:

### CODE REVIEW

**Comment by chebroluharika** [comment]
@AshuKV How did you make sure that code is under PEP8 standards

**Comment by chebroluharika** [comment]
@AshuKV can you please respond?

**Comment by AshuKV** [comment]
> @AshuKV can you please respond?

@chebroluharika  I would check once and let you know.

**Comment by yvkrishna** [comment]
@AshuKV any update on this pr ?

**Comment by AshuKV** [comment]
> @AshuKV How did you make sure that code is under PEP8 standards

I have updated all the python files referring this resource https://realpython.com/python-pep8/. Please let me know what more changes do I have to do.

**Comment by chebroluharika** [comment]
> > @AshuKV How did you make sure that code is under PEP8 standards
> 
> I have updated all the python files referring this resource https://realpython.com/python-pep8/. Please let me know what more changes do I have to do.

@AshuKV ideally you should write a workflow to check PEP8 standards for code

**Comment by chebroluharika** [comment]
@AshuKV I checked it from my end, it looks good.

**Pull request merged**
