### PR TITLE
Updated requirements.txt

### LINKED ISSUE #83: Requirements not updated
### **Describe the bug:**
Running `pip install -r requirements.txt` gives the following error:

image

### **To Reproduce:**
Please provide the steps to reproduce this bug/error:
This issue is faced when working in a virtual environment and trying to run any sample code from this package.  I think there are a few packages that are not yet updated in the requirements. The code in question is given below and was previously working before merging with the upstream.

```
from flow2ml import Flow

flow = Flow( 'dataset_dir' , 'data_dir' )
operations = {'crop': [50, 100, 50, 100]}
flow.applyAugmentation( operations )
```

### **Expected behavior:**
The code should run smoothly and free of errors after installing all the requirements. 

<hr/>

### PR DESCRIPTION
**Pull request by ArkaprabhaChakraborty**
# Description:

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #83 

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

 
# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

# Screenshots / Video:

### CODE REVIEW

**Comment by chebroluharika** [comment]
@ArkaprabhaChakraborty can you please attach screenshot showing successful execution of code

**Comment by ArkaprabhaChakraborty** [comment]
Uhh, I have tensorflow-gpu in my setup. And tensorflow and tensorflow-gpu clash with each other. I have added tensorflow into the requirements. But I cannot add tensorflow-gpu along with it.

**Comment by chebroluharika** [comment]
> Uhh, I have tensorflow-gpu in my setup. And tensorflow and tensorflow-gpu clash with each other. I have added tensorflow into the requirements. But I cannot add tensorflow-gpu along with it.

Are you sure if any one of package present in requirements file solve error or is it completely dependent on dataset size?

**Comment by ArkaprabhaChakraborty** [comment]
it isn't dependent on dataset size or something like that. It depends on whether tensorflow is there in the user's system or not. It's not completely a bug. Since Flow2ML installs all the prerequisite I added it to the requirements.

**Comment by chebroluharika** [comment]
> it isn't dependent on dataset size or something like that. It depends on whether tensorflow is there in the user's system or not. It's not completely a bug. Since Flow2ML installs all the prerequisite I added it to the requirements.

Only if you add required package in requirements.txt file, then only user will be able to get all required dependencies. Since you didn’t add it in prior it becomes a bug.

**Comment by chebroluharika** [comment]
> Yes, any one of the packages will do. For anyone who has tensorflow already its not a problem
> Screenshot from 2021-05-18 01-28-02
> Colab screenshot for successfull install of Flow2ML from my branch.

Here you are just cloning project which works obviously as that doesn’t depend on any dependencies. Please try to run any file and send me screenshot.

**Comment by ArkaprabhaChakraborty** [comment]
package doesn't install if requirements aren't made.

**Review by chebroluharika — APPROVED** [review]

**Pull request merged**
